### ISSUE TITLE
Bug: Clean DB types fails

### ISSUE THREAD

**Issue by MatanYadaev** [ballerine-io/ballerine#444]
### Description
The function `dropTypes` in `clean.ts` should drop Postgres' types, but fails.

It happens because the types are inserted in invalid order, and it tries to a type that is used by another type.

```
Invalid `prisma.$executeRawUnsafe()` invocation:
Raw query failed. Code: `2BP01`. Message: `db error: ERROR: cannot drop type "WorkflowRuntimeDataStatus"[] because type "WorkflowRuntimeDataStatus" requires it
HINT: You can drop type "WorkflowRuntimeDataStatus" instead.`
    at async dropTypes (/ballerine/ballerine/services/workflows-service/scripts/clean.ts:34:5)
```

### Expected Behaviour
The `clean.ts` should run without errors and clean the DB completely.

### Actual Behaviour
The `clean.ts` has errors and doesn't remove the Postgres' types.

### Steps to Reproduce
I think it's random and there are no predictable steps to reproduce.

**Comment by IsbosetA** [comment]
Invalid `prisma.$executeRawUnsafe()` invocation:
Raw query failed. Code: `2BP01`. Message: `db error: ERROR: cannot drop type "EndUserState"[] because type "EndUserState" requires it
HINT: You can drop type "EndUserState" instead.`
 at dropTypes (/home/ballerine-v2/ballerine/services/workflows-service/scripts/clean.ts:34:5)

I got the same error but with another type, I would like to know a temporary solution, so that clean.ts can be executed correctly.
